[tool.poetry]
name = "digital_pathology"
version = "1.0.0"
description = "Digital Pathology"
authors = ["Israel Llorens <sanchezis@hotmail.com>"]
license = "(EUPL) v1.2"

[tool.poetry.dependencies]
numpy = "^1.20.2"
pandas = "^2.0.0"
pyarrow = "^12.0.0"

pyspark = "3.5.1"
python = "^3.11"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
mypy = "^1.6.1"
black = "^23.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
