[tool.poetry]
name = "digital_pathology"
version = "1.0.0"
description = "Digital Pathology"
authors = ["Israel Llorens <sanchezis@hotmail.com>"]
license = "(EUPL) v1.2"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.20.2"
pandas = "^2.0.0"
pyspark = "3.5.1"
pyarrow = "14.0.2"  # Use a newer version with pre-built wheels

[tool.poetry.group.dev.dependencies]
mypy = "^1.6.1"
black = "^23.10.0"
pytest = "^7.4.4"
pytest-cov = "^4.1.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"
pytest-cov = "^4.1.0"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.poetry.group.doc.dependencies]
black = "^23.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
